server:
  port: 8002
spring:
  application:
    name: eureka-provider                   # 如果有多个同样的服务，这个名字要一样，否则 ribbon根据服务名调用进行负载均衡的时候,不能负载均衡
eureka:
  instance:
#    hostname: eureka8002.com
    instance-id: eureka-provider-2          # eureka 服务端显示注册实例 status列显示的名字
    prefer-ip-address: true                 # eureka 服务端显示注册实例 status列，鼠标放上去，左下角显示ip地址
  client:
#    register-with-eureka: false
#    fetch-registry: false
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka,http://eureka7003.com:7003/eureka
info:                                       # eureka 服务端显示注册实例 status点击的时候，打开页面可以显示 下面的信息
  app.name: com.cloud.blog                  # 需要引入 actuator依赖
  company.name: blog
  build.artifactId: $project.artifactId$
  build.version: $project.version$
