server:
  port: 7003
spring:
  application:
    name: eureka-server-3
eureka:
  instance:
    hostname: eureka7003.com                    # eureka DS Replicas 下面显示的 eureka服务端名称
    instance-id: eureka-server-3                # 这个在 eureka 服务端好像没用
    prefer-ip-address: true                     # eureka 左下角显示ip地址
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka
